image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay

before_script:
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

build_master:
  stage: build
  script:
    - docker pull "$CI_REGISTRY_IMAGE:latest" || echo Ignoring missing image
    - docker build -t "$CI_REGISTRY_IMAGE:latest" --cache-from "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

build_branch_or_tag:
  stage: build
  script:
    - docker pull "$CI_REGISTRY_IMAGE:latest" || echo Ignoring missing image
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_SLUG" --cache-from "$CI_REGISTRY_IMAGE:latest"  .
    - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_SLUG"
  except:
    - master # non-master branches and tags
